"""Inline the charts into the report so it is one self-contained file.

    python -m scripts.build_report        # report/index.html -> report/build/index.html

The report is written by hand in report/index.html and refers to the charts by
path. Anywhere it gets published — an artifact, an attachment, a page behind a
strict CSP — those paths do not resolve, so the build step turns every
<img src="charts/x.png"> into a data URI.

Nothing else is rewritten: prose stays editable in the source file, and the
charts stay generated by plot_bench.py from the JSON.
"""

from __future__ import annotations

import base64
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "report" / "index.html"
OUT = ROOT / "report" / "build" / "index.html"


def main() -> int:
    html = SRC.read_text()
    missing: list[str] = []

    def inline(match: re.Match) -> str:
        rel = match.group(1)
        # Charts live in bench/charts; the report refers to them as charts/*.png
        # so that the source file also renders when opened from a copy of that
        # directory next to it.
        path = ROOT / "bench" / rel
        if not path.exists():
            missing.append(rel)
            return match.group(0)
        blob = base64.b64encode(path.read_bytes()).decode()
        return f'src="data:image/png;base64,{blob}"'

    html = re.sub(r'src="([^"]+\.png)"', inline, html)
    if missing:
        # Loud rather than silent: a report published with a broken image looks
        # like a report with no evidence in it.
        raise SystemExit(f"missing charts: {', '.join(missing)}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(html)
    print(f"-> {OUT}  ({len(html) / 1e6:.2f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
